//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 20/04/2018 15:36:26
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace CadastroEpi.Domain.Model
{

    /// <summary>
    /// There are no comments for CadastroEpi.Domain.Model.TipoIdentificador in the schema.
    /// </summary>
    public enum TipoIdentificador : int
    {
    
        /// <summary>
        /// There are no comments for TipoIdentificador.CNPJ in the schema.
        /// </summary>
        CNPJ,    
        /// <summary>
        /// There are no comments for TipoIdentificador.CPF in the schema.
        /// </summary>
        CPF
    }

}
