//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 20/04/2018 15:36:26
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace CadastroEpi.Domain.Model
{

    /// <summary>
    /// There are no comments for CadastroEpi.Domain.Model.Empresa in the schema.
    /// </summary>
    public partial class Empresa    {

        public Empresa()
        {
            OnCreated();
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for EmpresaId in the schema.
        /// </summary>
        public virtual int EmpresaId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for RazaoSocial in the schema.
        /// </summary>
        public virtual string RazaoSocial
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for TipoIdentificador in the schema.
        /// </summary>
        public virtual TipoIdentificador TipoIdentificador
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Identificador in the schema.
        /// </summary>
        public virtual string Identificador
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for Funcoes in the schema.
        /// </summary>
        public virtual ICollection<Funcao> Funcoes
        {
            get;
            set;
        }

        #endregion
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
    }

}
