//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 20/04/2018 15:36:26
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace CadastroEpi.Domain.Model
{

    /// <summary>
    /// There are no comments for CadastroEpi.Domain.Model.FuncionarioEpi in the schema.
    /// </summary>
    public partial class FuncionarioEpi    {

        public FuncionarioEpi()
        {
            OnCreated();
        }


        #region Properties
    
        /// <summary>
        /// There are no comments for FuncionarioEpiId in the schema.
        /// </summary>
        public virtual int FuncionarioEpiId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DatEntrega in the schema.
        /// </summary>
        public virtual global::System.DateTimeOffset DatEntrega
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for DatTroca in the schema.
        /// </summary>
        public virtual global::System.Nullable<System.DateTimeOffset> DatTroca
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for FuncionarioId in the schema.
        /// </summary>
        public virtual int FuncionarioId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for EpiId in the schema.
        /// </summary>
        public virtual int EpiId
        {
            get;
            set;
        }


        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// There are no comments for Funcionario in the schema.
        /// </summary>
        public virtual Funcionario Funcionario
        {
            get;
            set;
        }
    
        /// <summary>
        /// There are no comments for Epi in the schema.
        /// </summary>
        public virtual Epi Epi
        {
            get;
            set;
        }

        #endregion
    
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
    }

}
